In [1]:
import pandas as pd
import json 
import pickle

# Input data

JESTR requires two inputs. We provide example input files in data/sample

1. data.tsv: spectra data and metadata (Only spectra with the fold column set as 'test' will be evaluated)
2. identifier_to_candidates.json: a mapping from identifier to a list of candidate smiles

In [2]:
# Main data file includes spectra and metadata
data = pd.read_csv("data/sample/data.tsv", sep="\t")
data[data['fold'] == 'test'].head()

,identifier,mzs,intensities,fold,precursor_mz
90,MassSpecGymID0214213,"42.033794,44.979271,86.05986,91.054344,93.0697...","0.01295,0.02273,0.10204,0.00936,0.00475,0.0077...",test,369.16312
91,MassSpecGymID0028002,"65.0385,68.997,77.0385,78.0461,79.0542,89.0386...","0.00999864,0.01208502,0.03910268,0.01290928,0....",test,404.12410
92,MassSpecGymID0336974,"247.044998,385.151001,464.252991,465.253998,48...","0.005,0.103,0.034,0.048,0.874,1.0,0.008,0.162",test,767.49000
93,MassSpecGymID0030233,"141.9831,142.9913,170.0148,176.044,177.0515,18...","0.00999201,0.00636254,0.011405559999999999,0.0...",test,374.09340
94,MassSpecGymID0221881,"68.049377,79.054039,80.04937,84.044296,91.0540...","0.03041,0.14939,0.08069000000000001,0.06174,0....",test,771.33616

In [ ]:
# candidate mapping from identifier to a list of candidate smiles
with open("data/sample/identifier_to_candidates.json", "r") as f:
    identifier_to_candidates = json.load(f)

identifier_to_candidates['MassSpecGymID0214213'][0:10]

['CC1=CC=CC=C1SCC(=O)N/N=C\\2/CCCC3=C2C(=CC(=C3)OC)C',
 'C[C@H]1CCN1c1nc(-c2noc(C3CCNCC3)n2)cc(C(F)(F)F)n1',
 'COC(=O)CC(C)(NC(=O)Cc1c[nH]c2ccccc12)c1ccc(F)cc1',
 'CN(C)CCNc1nc(NC(=O)c2cccc(N)c2)cc(C(F)(F)F)n1',
 'Cc1c(/N=C(\\N)Cc2cc(C(F)F)ccn2)nc(N)nc1-c1ccccc1',
 'COC(=O)c1occ(C(=O)OCC2CCCC(N)CNC2)c(=O)c1OC',
 'Cc1ccccc1CCNC(=O)CN(Cc1ccco1)Cc1cccs1',
 'CCC(=O)N(Cc1ccc(F)cc1)Cc1cc2cc(OC)ccc2[nH]c1=O',
 'CC(C)NC(CNC(=O)c1cc(CS)cc(CS)c1)C(=O)C(C)C',
 'Cc1oc2ccc(OCc3ccccc3)cc2c1C(=O)N[C@@H]1CNC[C@H]1F']

# JESTR output

The output file is a dataframe containing the sorted candidates and their scores

In [15]:
with open("experiments/20260321_FAISS_sample_run_1/result_test.pkl", "rb") as f:
    result = pickle.load(f)

result.head()

             identifier  \
0  MassSpecGymID0000201
1  MassSpecGymID0000219
2  MassSpecGymID0000403
3  MassSpecGymID0000472
4  MassSpecGymID0000586

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   sorted_candidates  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [CCCCCCCC(=O)Oc1ccc(-c2nc(-c3ccc(OC(=O)CCCCCCC)cc3O)nc(-c3ccc(OC(=O)CCCCCCC)cc3O)n2)c(O)c1, CCCCC(CC)C(=O)Oc1ccc(-c2nc(-c3ccc(OC(=O)C(CC)CCCC)cc3O)nc(-c3ccc(OC(=O)C(CC)CCCC)cc3O)n2)c(O)c1, COCCCN1C(=O)COc2ccc(N(C(=O)[C@H]3CN(C(=O)OC(C)(C)C)CC[C@@H]3c3cccc(-c4ccc(OCCOC5CCCCO5)cc4)c3)C3CC3)cc21, CCCCCCCC(=O)Oc1ccc(-n2c(=O)n(-c3ccc(OC(=O)CCCCCCC)cc3)c(=O)n(-c3ccc(OC(=O)CCCCCCC)cc3)c2=O)cc1, C=CCOC12Oc3ccc(OC(=O)NCC)cc3C3C(CCCCO)C(CCCCO)C=C(C(=NOC)CC1N(Cc1cccc4ccccc14)C(=O)OCC)C32, C=CCOC12Oc3ccc(OC(=O)NCC)cc3C3C(CCCCO)C(CCCCO)C=C(C(=NOCC)CC1N(Cc1cccc4ccccc14)C(=O)OC)C32, CC(=O)O[C@@H](C)/C=C\C(=O)N[C@@H]1C[C@H](C)[C@H](C/C=C(C)/C=C/[C@@H]2C[C@]3(CO3)C[C@@H](CNC(=O)CCNC(=O)OCC3c4ccccc4-c4ccccc43)O2)O[C@@H]1C, CC(=O)O[C@@H](C)/C=C\C(=O)N[C@@H]1C[C@H](C)[C@H](C/C=C(C)/C=C/[C@@H]2C[C@]3(CO3)C[C@@H](CC(=O)NCCNC(=O)OCC3c4ccccc4-c4ccccc43)O2)O[C@@H]1C, COCCCN1C(=O)COc2ccc(N(C(=O)[C@H]3CN(C(=O)OC(C)(C)C)CC[C@@H]3c3cccc(-c4cccc(OCCOC5CCCCO5)c4)c3)C3CC3)cc21, COC(=O)/C(C)=C\CC1(O)C(=O)C2CC(C(C)C)C13Oc1c(CC=C(C)C)c4c(c(OCNCCO)c1C(=O)C3C2C(C#N)C#N)C=CC(C)(CCC=C(C)C)O4, COC(=O)[C@@H]1CCCN1C(=O)[C@H](C)NC(=O)[C@H](CC(C)C)NC(=O)/C=C/[C@H]1O[C@@H](C)[C@@H](OCc2ccccc2)[C@@H](OCc2ccccc2)[C@@H]1OCc1ccccc1, O=C(O)C[C@H](NC(=O)C[C@H](NC(=O)C[C@H](NC(=O)OCC1c2ccccc2-c2ccccc21)C(=O)C1CCCCC1)C(=O)C1CCCCC1)C(=O)C1CCCCC1, CC(C)[C@H](CC(=O)[C@H](CCCCOC(=O)c1ccccc1)NC(=O)OC(C)(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)N1CCC[C@@H]1C(=O)OCc1ccccc1, CC(C)[C@H](CC(=O)[C@@H](CCCCOC(=O)c1ccccc1)NC(=O)OC(C)(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)N1CCC[C@@H]1C(=O)OCc1ccccc1, CCC(C)C1OC(=O)C(Cc2ccccc2)N(C)C(=O)C(C(C)C)OC(=O)C(Cc2ccccc2)N(C)C(=O)C(C(C)C)OC(=O)C(Cc2ccccc2)NC1=O, C=CC(CCN(C(=O)OCC1c2ccccc2-c2ccccc21)[C@@H](CCCCNC(=O)OCc1ccccc1)C(=O)OC)[C@H]1COC(C)(C)N1C(=O)OC(C)(C)C, C[C@H](CCC(=O)ON1C(=O)CCC1=O)[C@H]1CC[C@H]2[C@@H]3CC[C@@H]4C[C@@](O)(NC(=O)CNC(=O)OCC5c6ccccc6-c6ccccc65)CC[C@]4(C)[C@H]3C[C@H](O)[C@]12C, C=CCO[C@@]12Oc3ccc(OC(=O)NCC)cc3[C@H]3[C@H](CCCCO)[C@@H](CCCCO)C=C(C(=NOCC)C[C@@H]1N(Cc1cccc4ccccc14)C(=O)OC)[C@H]32, C=CCO[C@@]12Oc3ccc(OC(=O)NCC)cc3[C@H]3[C@H](CCCCO)[C@@H](CCCCO)C=C(C(=NOC)C[C@@H]1N(Cc1cccc4ccccc14)C(=O)OCC)[C@H]32, CCC(C)[C@H]1OC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C@@H](C(C)C)OC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C@@H](C(C)C)OC(=O)[C@H](Cc2ccccc2)NC1=O, CC(C)C1C(=O)OC(Cc2ccccc2)C(=O)N(C)C(C(C)C)C(=O)OC(Cc2ccccc2)C(=O)N(C)C(C(C)C)C(=O)OC(Cc2ccccc2)C(=O)N1C, CC(C)C1C(=O)O[C@H](Cc2ccccc2)C(=O)N(C)C(C(C)C)C(=O)O[C@H](Cc2ccccc2)C(=O)N(C)C(C(C)C)C(=O)O[C@H](Cc2ccccc2)C(=O)N1C, CC(C)[C@H]1C(=O)O[C@H](Cc2ccccc2)C(=O)N(C)[C@@H](C(C)C)C(=O)O[C@H](Cc2ccccc2)C(=O)N(C)[C@@H](C(C)C)C(=O)O[C@H](Cc2ccccc2)C(=O)N1C, CC(C)[C@@H]1C(=O)N([C@H](C(=O)O[C@@H](C(=O)N([C@H](C(=O)O[C@@H](C(=O)N([C@H](C(=O)O1)CC2=CC=CC=C2)C)C(C)C)CC3=CC=CC=C3)C)C(C)C)CC4=CC=CC=C4)C, CC(C)(C)OC(=O)ON1CC(COC(=O)NCCN2CCOCC2)C(c2ccc(OCCCOCc3ccccc3)cc2)C(OCc2ccc3ccccc3c2)C1, CC(C)CCC(=O)N1Cc2cc(cc(C(=O)O)c2)CN(C(=O)CCC(C)C)Cc2cc(cc(C(=O)O)c2)CN(C(=O)CCC(C)C)Cc2cc(cc(C(=O)O)c2)C1]

In [18]:
# print recall metrics
print("Recall@1: ", result['hit_rate@1'].mean())
print("Recall@5: ", result['hit_rate@5'].mean())
print("Recall@20: ", result['hit_rate@20'].mean())

Recall@1:  0.11394016549968174
Recall@5:  0.31826861871419476
Recall@20:  0.5789306174411203

In [14]:
#print first row completely 
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)
print(result.iloc[0].to_string())

identifier                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             MassSpecGymID0000201
sorted_candidates    [CCCCCCCC(=O)Oc1ccc(-c2nc(-c3ccc(OC(=O)CCCCCCC)cc3O)nc(-c3ccc(OC(=O)CCCCCCC)cc3O)n2)c(O)c1, CCCCC(CC)C(=O)Oc1ccc(-c2nc(-c3ccc(OC(=O)C(CC)CCCC)cc3O)nc(-c3ccc(OC(=O)C(CC)CCCC)cc3O)n2)c(O)c1, COCCCN1C(=O)COc2ccc(N(C(=O)[C@H]3CN(C(=O)OC(C)(C)C)CC[C@@H]3c3cccc(-c4ccc(OCCOC5CCCCO5)cc4)c3)C3CC3)cc21, CCCCCCCC(=O)Oc1ccc(-n2c(=O)n(-c3ccc(OC(=O)CCCCCCC)cc3)c(=O)n(-c3ccc(OC(=O)CCCCCCC)cc3)c2=O)cc1, C=CCOC12Oc3ccc(OC(=O)NCC)cc3C3C(CCCCO)C(CCCCO)C=C(C(=NOC)CC1N(Cc1cccc4ccccc14)C(=O)OCC)C32, C=CCOC12Oc3ccc(OC(=O)NCC)cc3C3C(CCCCO)C(CCCCO)C=C(C(=NOCC)CC1N(Cc1cccc4ccccc14)C(=O)OC)C32, CC(=O)O[C@@H](C)/C=C\C(=O)N[C@@H]1C[C@H](C)[C@H](C/C=C(C)/C=C/[C@@H]2C[C@]3(CO3)C[C@@H](CNC(=O)CCNC(=O)OCC3c4ccccc4-c4ccccc43)O2)O[C@@H]1C, CC(=O)O[C@@H](C)/C=C\C(=O)N[C@@H]1C[C@H](C)[C@H](C/C=C(C)/C=C/[C@@H]2C[C@]3(CO3)C[C@@H](CC(=O)NCCNC(=O)OCC3c4ccccc4-c4ccccc43)O2)O[C@@H]1C, COCCCN1C(=O)COc2ccc(N(C(=O)[C@H]3CN(C(=O)OC(C)(C)C)CC[C@@H]3c3cccc(-c4cccc(OCCOC5CCCCO5)c4)c3)C3CC3)cc21, COC(=O)/C(C)=C\CC1(O)C(=O)C2CC(C(C)C)C13Oc1c(CC=C(C)C)c4c(c(OCNCCO)c1C(=O)C3C2C(C#N)C#N)C=CC(C)(CCC=C(C)C)O4, COC(=O)[C@@H]1CCCN1C(=O)[C@H](C)NC(=O)[C@H](CC(C)C)NC(=O)/C=C/[C@H]1O[C@@H](C)[C@@H](OCc2ccccc2)[C@@H](OCc2ccccc2)[C@@H]1OCc1ccccc1, O=C(O)C[C@H](NC(=O)C[C@H](NC(=O)C[C@H](NC(=O)OCC1c2ccccc2-c2ccccc21)C(=O)C1CCCCC1)C(=O)C1CCCCC1)C(=O)C1CCCCC1, CC(C)[C@H](CC(=O)[C@H](CCCCOC(=O)c1ccccc1)NC(=O)OC(C)(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)N1CCC[C@@H]1C(=O)OCc1ccccc1, CC(C)[C@H](CC(=O)[C@@H](CCCCOC(=O)c1ccccc1)NC(=O)OC(C)(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)N1CCC[C@@H]1C(=O)OCc1ccccc1, CCC(C)C1OC(=O)C(Cc2ccccc2)N(C)C(=O)C(C(C)C)OC(=O)C(Cc2ccccc2)N(C)C(=O)C(C(C)C)OC(=O)C(Cc2ccccc2)NC1=O, C=CC(CCN(C(=O)OCC1c2ccccc2-c2ccccc21)[C@@H](CCCCNC(=O)OCc1ccccc1)C(=O)OC)[C@H]1COC(C)(C)N1C(=O)OC(C)(C)C, C[C@H](CCC(=O)ON1C(=O)CCC1=O)[C@H]1CC[C@H]2[C@@H]3CC[C@@H]4C[C@@](O)(NC(=O)CNC(=O)OCC5c6ccccc6-c6ccccc65)CC[C@]4(C)[C@H]3C[C@H](O)[C@]12C, C=CCO[C@@]12Oc3ccc(OC(=O)NCC)cc3[C@H]3[C@H](CCCCO)[C@@H](CCCCO)C=C(C(=NOCC)C[C@@H]1N(Cc1cccc4ccccc14)C(=O)OC)[C@H]32, C=CCO[C@@]12Oc3ccc(OC(=O)NCC)cc3[C@H]3[C@H](CCCCO)[C@@H](CCCCO)C=C(C(=NOC)C[C@@H]1N(Cc1cccc4ccccc14)C(=O)OCC)[C@H]32, CCC(C)[C@H]1OC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C@@H](C(C)C)OC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C@@H](C(C)C)OC(=O)[C@H](Cc2ccccc2)NC1=O, CC(C)C1C(=O)OC(Cc2ccccc2)C(=O)N(C)C(C(C)C)C(=O)OC(Cc2ccccc2)C(=O)N(C)C(C(C)C)C(=O)OC(Cc2ccccc2)C(=O)N1C, CC(C)C1C(=O)O[C@H](Cc2ccccc2)C(=O)N(C)C(C(C)C)C(=O)O[C@H](Cc2ccccc2)C(=O)N(C)C(C(C)C)C(=O)O[C@H](Cc2ccccc2)C(=O)N1C, CC(C)[C@H]1C(=O)O[C@H](Cc2ccccc2)C(=O)N(C)[C@@H](C(C)C)C(=O)O[C@H](Cc2ccccc2)C(=O)N(C)[C@@H](C(C)C)C(=O)O[C@H](Cc2ccccc2)C(=O)N1C, CC(C)[C@@H]1C(=O)N([C@H](C(=O)O[C@@H](C(=O)N([C@H](C(=O)O[C@@H](C(=O)N([C@H](C(=O)O1)CC2=CC=CC=C2)C)C(C)C)CC3=CC=CC=C3)C)C(C)C)CC4=CC=CC=C4)C, CC(C)(C)OC(=O)ON1CC(COC(=O)NCCN2CCOCC2)C(c2ccc(OCCCOCc3ccccc3)cc2)C(OCc2ccc3ccccc3c2)C1, CC(C)CCC(=O)N1Cc2cc(cc(C(=O)O)c2)CN(C(=O)CCC(C)C)Cc2cc(cc(C(=O)O)c2)CN(C(=O)CCC(C)C)Cc2cc(cc(C(=O)O)c2)C1]
sorted_scores                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [0.2778393626213074, 0.2568429708480835, 0.12162542343139648, 0.1134457066655159, 0.09720821678638458, 0.09243399649858475, 0.07877547293901443, 0.07485782355070114, 0.07162830233573914, 0.05109415203332901, 0.03140070289373398, 0.011846523731946945, -0.005368236918002367, -0.005509341601282358, -0.048817433416843414, -0.05484045296907425, -0.08987842500209808, -0.09370101988315582, -0.10384809225797653, -0.11205048114061356, -0.12168119847774506, -0.13607989251613617, -0.15334677696228027, -0.16316285729408264, -0.2184664011001587, -0.23673267662525177]
sorted_labels                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False]
target_candidate                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              CC(C)[C@@H]1C(=O)N([C@H](C(=O)O[C@@H](C(=O)N([C@H](C(=O)O[C@@H](C(=O)N([C@H](C(=O)O1)CC2=CC=CC=C2)C)C(C)C)CC3=CC=CC=C3)C)C(C)C)CC4=CC=CC=C4)C
rank                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     24

In [4]:
with open("experiments/20260321_FAISS_sample_run_1/result_identifier_to_candidates.pkl", "rb") as f:
    result = pickle.load(f)

result.head()

,identifier,sorted_candidates,sorted_scores
0,MassSpecGymID0214213,[CC1=CC=CC=C1SCC(=O)N/N=C\2/CCCC3=C2C(=CC(=C3)...,"[0.49698513746261597, 0.4939979612827301, 0.49..."
1,MassSpecGymID0028002,[O=c1[nH]c2cnc(-n3cnc4cnccc43)nc2n1C1CCOc2c(F)...,"[0.6375532150268555, 0.6322932243347168, 0.620..."
2,MassSpecGymID0336974,[CC(=CCC(O)C(C)C1CCC2(C)C3CCC4C(C)(C)C(OC5OC(C...,"[0.4895637035369873, 0.48725855350494385, 0.46..."
3,MassSpecGymID0030233,[CC(=O)OC1=C(c2cc(-c3ccc(F)cc3)ccc2Cl)C(=O)C(C...,"[0.5568597316741943, 0.5509238839149475, 0.525..."
4,MassSpecGymID0221881,[Cc1cncc(C(CCC2CC2)(N[S@](=O)C(C)(C)C)c2ccc(F)...,"[0.5085124969482422, 0.48943737149238586, 0.47..."